CREATE TABLE banners (
  id INT(11) NOT NULL AUTO_INCREMENT,
  vendor_id INT(11) NOT NULL,
  banner_image VARCHAR(500) NOT NULL,
  alt_text VARCHAR(255) DEFAULT NULL,
  caption VARCHAR(500) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  sort_order INT(11) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_vendor_id (vendor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
